#!/bin/sh

# This program was written by Ben Weinstein-Raun in 2023 and 2024.
# Anyone may use it for any purpose, under the terms of the CC0-1.0
# License or the Apache 2.0 License, at the licensee's option. Both
# licenses are distributed with the program, in the files
# LICENSE-CC0.txt and LICENSE-APACHE.txt.

# Requirements:
# - coreutils (id)
# - daemontools (setuidgid)
# - shepherd
# - sudo

set -e -u

echo "path:$PATH"
username=$1
uid=$(id -u "$username")
gid=$(id -g "$username")

export XDG_RUNTIME_DIR="/run/user/$uid"
mkdir -p "$XDG_RUNTIME_DIR"
mount -t tmpfs -o "mode=0700,uid=$uid,gid=$gid" tmpfs "/run/user/$uid"

exec setuidgid "$username" shepherd
